### ISSUE TITLE
Support configuration option for dartfmt --fix

### ISSUE THREAD

**Issue by pschiffmann** [dart-lang/mono_repo#111]
https://github.com/dart-lang/dart_style#style-fixes

**Comment by kevmoo** [comment]
Explain? What do you want here?

**Comment by pschiffmann** [comment]
Sorry. I meant: Right now, I can only toggle the `dartfmt` task on or off, but I can't specify that it should check that all (or some) style fixes are applied.

So, one possible solution would be this:
```yaml
stages:
  - a:
    # Executes the command `dartfmt -n --set-exit-if-changed .`
    - dartfmt
  - b:
    # Executes the command `dartfmt -n --set-exit-if-changed --fix-optional-const --fix-optional-new .`
    - dartfmt: --fix-optional-const --fix-optional-new
```
