### ISSUE TITLE
stages in mono_repo

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/mono_repo#50]
```yaml
dart:
  - dev
  - stable

stages:
  - sample1: "valid dart task string name"
  - sample2:
    - "valid dart task string name"
    - script: "one line script invocation"
    - name: foo
      script:
        - "script1"
        - "script2"
    - dartanalyzer: --hints-as-warnings .
    - name: analyze_fun
      dartanalyzer:
    - name: analyze_fun2
      dartanalyzer: --hint-as-warnings .
    - name: analyze_fun3
      dartanalyzer:
  - analyze # ERROR! must have at least one action!
  - test #ERROR! not allowed!
  - sample1 #ERROR! duplicate!
  - first_in_another_.monorepo.yml #ERROR! ordering cannot contradict across...things

exclude:
  - dart: stable
    jobs:
      - foo
      - bar # ERROR! doesn't exist as a name above!
```

**Comment by kevmoo** [comment]
Better yet

```yaml
dart:
  - stable

stages:
  - sample1: "valid dart task string name"
  - sample2:
    - "valid dart task string name"
    - script: "one line script invocation"
    - dart:
         - 'dev'
         - 'stable'
      script:
        - "script1"
        - "script2"
    - dartanalyzer: --hints-as-warnings .
    - name: analyze_fun
      dartanalyzer:
    - name: analyze_fun2
      dartanalyzer: --hint-as-warnings .
    - name: analyze_fun3
      dartanalyzer:
  - analyze # ERROR! must have at least one action!
  - test #ERROR! not allowed!
  - sample1 #ERROR! duplicate!
  - first_in_another_.monorepo.yml #ERROR! ordering cannot contradict across...things
```

**Comment by jakemac53** [comment]
cc @matanlurey @natebosch @alorenzen basically the idea is to replace the `.travis.yml` files in your packages with `.mono_repo.yaml` files with this format.

**Comment by jakemac53** [comment]
Realistic example for build_runner:

```yaml
dart:
  - dev
  - stable
stages:
  - analyze_and_format:
    - dartanalyzer: --hints-as-warnings .
    - dartfmt: sdk
      dart:
        - dev
  - build:
    - script: "pub run build_runner build"
  - test:
    - script: "pub run build_runner test"
    - script: "pub run build_runner test -- -p chrome"
```
