### ISSUE TITLE
A way to retain sudo:/addons:

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mono_repo#55]
I need this today:

```yaml
# MANUALLY ADDED. Do not remove.
# Gives more resources on Travis (8GB Ram, 2 CPUs).
# Do not remove without verifying w/ Travis.
sudo: required
addons:
  chrome: stable
# END MANUAL EDITS.
```
