### ISSUE TITLE
A way to retain cache:

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/mono_repo#56]
I need this today:

```yaml
cache:
  directories:
    - $HOME/.pub-cache
    # MANUALLY ADDED. Do not remove.
    - _benchmarks/.dart_tool
    - _goldens/.dart_tool
    - angular_router/.dart_tool
    - angular_test/.dart_tool
    # END MANUAL EDITS.
```
